version: '3.8'

services:
  servicea:
    build:
      context: .
      dockerfile: serviceA/Dockerfile
      target: development
    container_name: two-services-servicea-dev
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
    env_file:
      - .env
    volumes:
      - ./serviceA/src:/app/two-services-servicea/src
      - ./serviceA/package.json:/app/two-services-servicea/package.json
    networks:
      - microservices-network
    depends_on:
      - mongodb
      - redis
      - redis-pubsub
      - serviceb

  serviceb:
    build:
      context: .
      dockerfile: serviceB/Dockerfile
      target: development
    container_name: two-services-serviceb-dev
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - PORT=3001
    env_file:
      - .env
    volumes:
      - ./serviceB/src:/app/two-services-serviceb/src
      - ./serviceB/package.json:/app/two-services-serviceb/package.json
    networks:
      - microservices-network
    depends_on:
      - mongodb
      - redis
      - redis-pubsub
      - redis-timeseries

  # Data Services
  mongodb:
    image: mongo:7.0
    container_name: two-services-mongodb-dev
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=two-services
    volumes:
      - mongodb-dev-data:/data/db
      - ./docker/mongodb/init:/docker-entrypoint-initdb.d
    networks:
      - microservices-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  redis:
    image: redis:7.2-alpine
    container_name: two-services-redis-dev
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes --requirepass password
    volumes:
      - redis-dev-data:/data
      - ./docker/redis/redis.conf:/usr/local/etc/redis/redis.conf
    networks:
      - microservices-network
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "password", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s

  redis-timeseries:
    image: redislabs/redistimeseries:latest
    container_name: two-services-redis-timeseries-dev
    ports:
      - "6380:6379"
    command: redis-server --loadmodule /usr/lib/redis/modules/redistimeseries.so --appendonly yes --requirepass password
    volumes:
      - redis-timeseries-dev-data:/data
    networks:
      - microservices-network
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "password", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s

  redis-pubsub:
    image: redis:7.2-alpine
    container_name: two-services-redis-pubsub-dev
    ports:
      - "6381:6379"
    command: redis-server --requirepass password
    volumes:
      - redis-pubsub-dev-data:/data
    networks:
      - microservices-network
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "password", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s

  pdf-generator:
    build:
      context: ./pdf-generator
      dockerfile: Dockerfile
    container_name: two-services-pdf-generator-dev
    ports:
      - "50051:50051"
    environment:
      - GRPC_PORT=50051
      - REDIS_TIMESERIES_ADDR=redis-timeseries:6379
      - REDIS_PASSWORD=password
    volumes:
      - ./pdf-generator:/app
    networks:
      - microservices-network
    depends_on:
      - redis-timeseries
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "50051"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

volumes:
  mongodb-dev-data:
    driver: local
  redis-dev-data:
    driver: local
  redis-timeseries-dev-data:
    driver: local
  redis-pubsub-dev-data:
    driver: local

networks:
  microservices-network:
    driver: bridge
